tabWidth: 4
semi: false
singleQuote: true
jsxSingleQuote: true
trailingComma: all
htmlWhitespaceSensitivity: ignore

# prettier-plugin-tailwindcss 플러그인 때문에 사용하는 플러그인 직접 명시해야 함
# https://github.com/tailwindlabs/prettier-plugin-tailwindcss#compatibility-with-other-prettier-plugins
plugins:
  - 'prettier-plugin-svelte'
  - 'prettier-plugin-tailwindcss'
pluginSearchDirs: false

overrides:
  - files:
      - '*.yml'
      - '*.yaml'
      - '*.json'
    options:
      tabWidth: 2
